spring:
  application:
    name: rabbitmq-sender-direct
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: 123456
    #虚拟host 可以不设置,使用server默认host
    virtual-host: testHost